import * as Yup from 'yup';
import registrationFormModel from './RegistrationFormModel';
const {
	formField: {
		institutionName,
		memberShipCategory,
		registrationNumber,
		contactPerson,
		designation,
		telephoneContact,
		email,
		emailAddress,
		soleProprietorShip,
		partnership,
		parish,
		village,
		limitedCompany,
		licenseNumber,
		registered,
		ownerNIN,
		ownerName,
		otherOwnershipType,
		regNumber,
		mixed,
		single,
		boarding,
		day,
		subCounty,
		district,
		contact,
		website,
		enrollment,
		teachingStaffFemale,
		teachingStaffMale,
	},
} = registrationFormModel;

export default [
	Yup.object().shape({
		[institutionName.name]: Yup.string().required(
			`${institutionName.requiredErrorMsg}`
		),
		[memberShipCategory.name]: Yup.string().required(`${memberShipCategory.requiredErrorMsg}`),
		[registrationNumber.name]: Yup.string().required(`${registrationNumber.requiredErrorMsg}`),
		[contactPerson.name]: Yup.string().required(`${contactPerson.requiredErrorMsg}`),
		[designation.name]: Yup.string().required(`${designation.requiredErrorMsg}`),
		[telephoneContact.name]: Yup.string().required(`${telephoneContact.requiredErrorMsg}`),
		[email.name]: Yup.string().required(`${email.requiredErrorMsg}`).email(),
		[emailAddress.name]: Yup.string().required(`${emailAddress.requiredErrorMsg}`).email(),
		[soleProprietorShip.name]: Yup.string().required(`${soleProprietorShip.requiredErrorMsg}`),
		[partnership.name]: Yup.string().required(`${partnership.requiredErrorMsg}`),
		[parish.name]: Yup.string().required(`${parish.requiredErrorMsg}`),
		[village.name]: Yup.string().required(`${village.requiredErrorMsg}`),
		[limitedCompany.name]: Yup.string().required(`${limitedCompany.requiredErrorMsg}`),
		[licenseNumber.name]: Yup.string().required(`${licenseNumber.requiredErrorMsg}`),
		[registered.name]: Yup.string().required(`${registered.requiredErrorMsg}`),
		[ownerNIN.name]: Yup.string().required(`${ownerNIN.requiredErrorMsg}`),
		[ownerName.name]: Yup.string().required(`${ownerName.requiredErrorMsg}`),
		[otherOwnershipType.name]: Yup.string().required(`${otherOwnershipType.requiredErrorMsg}`),
		[regNumber.name]: Yup.string().required(`${regNumber.requiredErrorMsg}`),
		[mixed.name]: Yup.string().required(`${mixed.requiredErrorMsg}`),
		[single.name]: Yup.boolean().required(`${single.requiredErrorMsg}`),
		[boarding.name]: Yup.string().required(`${boarding.requiredErrorMsg}`),
		[day.name]: Yup.string().required(`${day.requiredErrorMsg}`),
		[subCounty.name]: Yup.string().required(`${subCounty.requiredErrorMsg}`),
		[district.name]: Yup.string().required(`${district.requiredErrorMsg}`),
		[contact.name]: Yup.string().required(`${contact.requiredErrorMsg}`),
		[website.name]: Yup.string().required(`${website.requiredErrorMsg}`),
		[enrollment.name]: Yup.string().required(`${enrollment.requiredErrorMsg}`),
		[teachingStaffFemale.name]: Yup.string().required(`${teachingStaffFemale.requiredErrorMsg}`),
		[teachingStaffMale.name]: Yup.string().required(`${teachingStaffMale.requiredErrorMsg}`),

	}),
];
